### ISSUE TITLE
Downloading the data

### ISSUE THREAD

**Issue by AliKarimirad** [ubcecon/MacroReadingGroup#2]
Hi,
I downloaded form 2000 to  2017
Please download from 1990 to 1999. by Monday

**Comment by wupeifan** [comment]
Is there anything that I should be aware of regarding the reading group, or it's something else?

**Comment by AliKarimirad** [comment]
Hi,
I did a mistake and create an issue in wrong location.
I closed it.
Sorry for the trouble.
Best Regards,

*Ali KarimiradPhD student at University of British Columbia. *
*Email: a.karimirad@a <akarimir@asu.edu>lumni.ubc.ca <http://lumni.ubc.ca>*
